#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Ruta para el controlador user #


user:
    path: /user
    controller: App\Controller\UserController::index
    methods: [GET]


register:
    path: /register
    controller: App\Controller\UserController::create
    methods: [POST]
    
 
login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]

update:
    path: /user/update
    controller: App\Controller\UserController::update
    methods: [PUT]    
       

# Ruta para el controlador video #

video:
    path: /video
    controller: App\Controller\VideoController::index
    methods: [POST]

newVideo:
    path: /video/new
    controller: App\Controller\VideoController::create
    methods: [POST]

editVideo:
    path: /video/update/{id}
    controller: App\Controller\VideoController::create
    methods: [PUT]

ListarVideo:
    path: /video/list
    controller: App\Controller\VideoController::listarVideos
    methods: [GET]

ListarVideoPorID:
    path: /video/detail/{id}
    controller: App\Controller\VideoController::videoPorId
    methods: [GET]   
 
RemoveVideo:
    path: /video/remove/{id}
    controller: App\Controller\VideoController::removeVideo
    methods: [DELETE]  
   
