#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Ruta para el controlador user #
user:
    path: /user
    controller: App\Controller\UserController::index

# Ruta para el controlador video #

video:
    path: /video
    controller: App\Controller\VideoController::index
